parameters:
  ez_migration_bundle.complex.field.manager.class: Kaliop\eZMigrationBundle\Core\API\ComplexFields\ComplexFieldManager
  ez_migration_bundle.handler.role.class: Kaliop\eZMigrationBundle\Core\API\Handler\RoleTranslationHandler
  kaliop_bundle_migration.version_directory: 'MigrationVersions'
  kaliop_bundle_migration.table_name: 'kaliop_versions'
  ez_migration_bundle.complex.field.ezimage.class: Kaliop\eZMigrationBundle\Core\API\ComplexFields\EzImage
  ez_migration_bundle.complex.field.ezbinaryfile.class: Kaliop\eZMigrationBundle\Core\API\ComplexFields\EzBinaryFile
  ez_migration_bundle.complex.field.ezxmltext.class: Kaliop\eZMigrationBundle\Core\API\ComplexFields\EzXmlText
  ez_migration_bundle.complex.field.ezpage.class: Kaliop\eZMigrationBundle\Core\API\ComplexFields\EzPage
  ez_migration_bundle.handler.location_resolver.class: Kaliop\eZMigrationBundle\Core\API\Handler\LocationResolverHandler
  ez_migration_bundle.location_resolver.repository_aware.class: Kaliop\eZMigrationBundle\Core\API\LocationResolver\AbstractRepositoryAwareLocationResolver
  ez_migration_bundle.location_resolver.location_remote_id.class: Kaliop\eZMigrationBundle\Core\API\LocationResolver\LocationRemoteIdLocationResolver

services:
  ez_migration_bundle.complex.field.manager:
    class: %ez_migration_bundle.complex.field.manager.class%
    arguments:
      - @ezpublish.api.repository
      - @service_container
      - # map of fieldtypes => classes implementing ComplexFieldInterface.
        ezimage: %ez_migration_bundle.complex.field.ezimage.class%
        ezbinaryfile: %ez_migration_bundle.complex.field.ezbinaryfile.class%
        ezxmltext: %ez_migration_bundle.complex.field.ezxmltext.class%
        ezpage: %ez_migration_bundle.complex.field.ezpage.class%
  ez_migration_bundle.handler.role:
    class: %ez_migration_bundle.handler.role.class%
    arguments:
      - @ezpublish.api.repository
      - @service_container
      - %ezpublish.siteaccess.list%
  ez_migration_bundle.handler.location_resolver:
    class: %ez_migration_bundle.handler.location_resolver.class%
  ez_migration_bundle.location_resolver.repository_aware:
    class: %ez_migration_bundle.location_resolver.repository_aware.class%
    abstract: true
    arguments:
      - @ezpublish.api.repository
  ez_migration_bundle.location_resolver.location_remote_id:
    class: %ez_migration_bundle.location_resolver.location_remote_id.class%
    parent: ez_migration_bundle.location_resolver.repository_aware
    tags:
      - { name: ez_migration_bundle.location_resolver }
