parameters:
  ez_migration_bundle.version_directory: 'MigrationVersions'
  ez_migration_bundle.table_name: 'kaliop_versions'

  ez_migration_bundle.complex.field.manager.class: Kaliop\eZMigrationBundle\Core\ComplexField\ComplexFieldManager
  ez_migration_bundle.handler.role.class: Kaliop\eZMigrationBundle\Core\Handler\RoleTranslationHandler
  ez_migration_bundle.complex.field.ezimage.class: Kaliop\eZMigrationBundle\Core\ComplexField\EzImage
  ez_migration_bundle.complex.field.ezbinaryfile.class: Kaliop\eZMigrationBundle\Core\ComplexField\EzBinaryFile
  ez_migration_bundle.complex.field.ezxmltext.class: Kaliop\eZMigrationBundle\Core\ComplexField\EzXmlText
  ez_migration_bundle.complex.field.ezrichtext.class: Kaliop\eZMigrationBundle\Core\ComplexField\EzRichText
  ez_migration_bundle.complex.field.ezpage.class: Kaliop\eZMigrationBundle\Core\ComplexField\EzPage
  ez_migration_bundle.handler.location_resolver.class: Kaliop\eZMigrationBundle\Core\Handler\LocationResolverHandler
  ez_migration_bundle.location_resolver.repository_aware.class: Kaliop\eZMigrationBundle\Core\LocationResolver\AbstractRepositoryAwareLocationResolver
  ez_migration_bundle.location_resolver.location_remote_id.class: Kaliop\eZMigrationBundle\Core\LocationResolver\LocationRemoteIdLocationResolver
  ez_migration_bundle.complex.field.ezauthor.class: Kaliop\eZMigrationBundle\Core\ComplexField\EzAuthor
  ez_migration_bundle.content_matcher.class: Kaliop\eZMigrationBundle\Core\Matcher\ContentMatcher

services:
  ez_migration_bundle.complex.field.manager:
    class: %ez_migration_bundle.complex.field.manager.class%
    arguments:
      - @ezpublish.api.repository
      - @service_container
      - # map of fieldtypes => classes implementing ComplexFieldInterface.
        ezimage: %ez_migration_bundle.complex.field.ezimage.class%
        ezbinaryfile: %ez_migration_bundle.complex.field.ezbinaryfile.class%
        ezxmltext: %ez_migration_bundle.complex.field.ezxmltext.class%
        ezpage: %ez_migration_bundle.complex.field.ezpage.class%
        ezauthor: %ez_migration_bundle.complex.field.ezauthor.class%
        ezrichtext: %ez_migration_bundle.complex.field.ezrichtext.class%

  ez_migration_bundle.handler.role:
    class: %ez_migration_bundle.handler.role.class%
    arguments:
      - @ezpublish.api.repository
      - @service_container
      - %ezpublish.siteaccess.list%

  ez_migration_bundle.handler.location_resolver:
    class: %ez_migration_bundle.handler.location_resolver.class%

  ez_migration_bundle.location_resolver.repository_aware:
    class: %ez_migration_bundle.location_resolver.repository_aware.class%
    abstract: true
    arguments:
      - @ezpublish.api.repository

  ez_migration_bundle.location_resolver.location_remote_id:
    class: %ez_migration_bundle.location_resolver.location_remote_id.class%
    parent: ez_migration_bundle.location_resolver.repository_aware
    tags:
      - { name: ez_migration_bundle.location_resolver }

  ez_migration_bundle.content_matcher:
    class: %ez_migration_bundle.content_matcher.class%
    arguments:
      - @ezpublish.api.inner_repository
