# Executing symfony Service method as migration step

-
    type: service
    mode: call
    service: logger # a string, or a reference
    method: debug # a string, or a reference
    arguments: # an array of arguments
        - 'hello world'
        - reference:someref # references will be resolved (if they occupy the whole argument; not if they part of of a bunch of text)
    # The list in references tells the manager to store specific values for later use by other steps in the current migration.
    # NB: these are NEW VARIABLES THAT YOU ARE CREATING. They are not used in the current migration step!
    references: # Optional
         -
            identifier: referenceId # A string used to identify the reference
            attribute: # An attribute to get the value of for the reference. Supports: result, exception_code, exception_message, exception_file, exception_line
